sudo: false
language: node_js
install: npm install
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '10'
before_script:
  - npm prune
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
